name: "Deploy delphai microservices to Azure kubernetes in delphai's Infrastructure"
description: "Deploy delphai microservices to Azure kubernetes in delphai's Infrastructure"
author: "delpahi/devops"
inputs:
  delphai_enviroment:
    description: 'Delphai Subscription Enviroment'
    required: true
  registry_password:
    description: 'Delphai Subscription Enviroment'
    required: true

runs:
  using: 'node12'
  main: 'src/start.sh'
branding:
  icon: 'anchor'
  color: 'blue'
  