name: "Deploy delphai microservices to Azure kubernetes in delphai's Infrastructure"
description: "Deploy delphai microservices to Azure kubernetes in delphai's Infrastructure"
author: "delpahi/devops"
inputs:
  delphai_enviroment:
    description: 'Delphai Emviroment'
    required: true
  client_id:
    description: 'Client Id'
    required: true
  client_secret:
    description: 'Client secret'
    required: true
  tenant_id:
    description: 'Tenant Id'
    required: true
  acr_secret:
    description: 'Registiry secret'
    required: true
  
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: 'anchor'
  color: 'blue'
  