name: "Deploy delphai microservices to Azure kubernetes in delphai's Infrastructure"
description: "Deploy delphai microservices to Azure kubernetes in delphai's Infrastructure"
author: 'delpahi/devops'
inputs:
  image_sha:
    description: 'Docker image SHA'
    required: false
  delphai_enviroment:
    description: 'delphai Emviroment'
    required: true
  client_id:
    description: 'Client Id'
    required: true
  client_secret:
    description: 'Client secret'
    required: true
  tenant_id:
    description: 'Tenant Id'
    required: true
  acr_secret:
    description: 'Registiry secret'
    required: true
  httpport:
    description: 'Http Port External'
    required: false
    default: '8080'
  grpcport:
    description: 'Http Port External'
    required: false
  is_public:
    description: 'External URL'
    required: false
    default: 'true'
  is_ui:
    description: 'if ui repo'
    required: false
    default: 'false'
  is_grpc:
    description: check if the repo grpc
    required: false
    default: 'false'
  microservice:
    description: 'Minimum Scaling to one pod'
    required: false
    default: 'false'
  file_shares:
    description: 'Specify the shared files as following *file1.txt,file2.txt*'
    required: false
  domains:
    description: 'specify many domain for helm'
    required: false
  subdomain:
    description: Subdomain for UI services
    required: false
  replicas:
    description: Number of replicas to deploy
    required: false
  min_scale:
    description: Minimum scale for knative service
    default: 1
  concurrency:
    description: Concurrency of knative service
    default: 100

runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'anchor'
  color: 'blue'
