name: "Deploy delphai microservices to Azure kubernetes in delphai's Infrastructure"
description: "Deploy delphai microservices to Azure kubernetes in delphai's Infrastructure"
author: "delpahi/devops"
inputs:
  delphai_enviroment:
    description: 'Delphai Subscription Enviroment'
    required: false
  

runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: 'anchor'
  color: 'blue'
  